[build]
  command = "npm run build"
  publish = "build"

# Redirect for all API calls to the Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Fallback redirect to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
